### ISSUE TITLE
Proposal to take over maintenance of rainbow-delimiters

### ISSUE THREAD

**Issue by purcell** [jlr/rainbow-delimiters#22]
Hi -- since it looks like you're not getting any time to handle issues & pull requests for this repo, @Fanael has [offered to take over](https://github.com/milkypostman/melpa/pull/1074), at which point we would start building [MELPA](http://melpa.milkbox.net/) packages from his fork.

Please comment here if you'd rather that didn't happen. I guess an alternative would be for you to just grant commit privileges to @Fanael, which might be less work all round, and would make it easier for you to collaborate if you end up with more time to do so.

-Steve

**Comment by purcell** [comment]
We've gone ahead and switched our recipe over to point at @Fanael's fork.

**Comment by jlr** [comment]
Totally legitimate. Sorry I have not been around to maintain it. I've been away from my desktop for months now and working in Apple's ecosystem. I would like to pick up maintainership in the future, but please proceed from here. Can I assist you in any way in the handoff? Should I place a notice on this page redirecting people to the new fork?

I am also willing to pick up maintainership within one month. I will be finally getting my desktop down here in San Francisco. From there I'll remain on top of things. So can we resume the process of integrating your work under this branch at that time? I shouldn't ever be disconnected from the community for such a long time again.

My apologies for not staying on top of this. People sending in patches involves real time and I appreciate it and am glad the mode is working well for people. I want to add many more features to it (e.g. HTML tag highlighting), and intend to continue it once I have a Linux system back in my life.

**Comment by jlr** [comment]
Now that I read the first comment - can we add Fanael to this branch as a maintainer? I'll look into adding him.

**Comment by jlr** [comment]
OK. I just added @Fanael and @purcell as Contributors. 

@purcell You've been helping with the mode for a while so I figured it made sense for you to be able to make changes if you saw fit.

I think staying on this github repo is the right approach despite the fact I wasted your time by causing you to fork. I intend to add more features to rainbow-delimiters myself and we should all be working on the same code base. I know I'm asking a bit of your time to reverse the steps you've taken the past day or two in terms of setting up a separate repo, new URL's, new MELPA packaging etc. I wish my timing had been better.

Then again, I put real time into constructing the code we have now :-)

I'm so glad to see the mode get used and be useful enough people actually will fork it if I don't stay on top of it! I'll definitely be proactive with it again once I finally get my desktop down here to SF. Thanks guys!

**Comment by purcell** [comment]
Thanks @jlr! Yep, impeccable timing. ;-)

Hey @Fanael, can you perhaps merge the changes in your fork back into this repo, and then we'll switch the recipe back?

**Comment by Fanael** [comment]
Merged the changes. Please go ahead and switch the recipe back.

**Comment by purcell** [comment]
Cool - I've switched the recipe back.

**Comment by Fanael** [comment]
By the way, I'm sorry for the mess I created in some issues by mentioning them in commits that I later amended and force-pushed a bunch of times. Is there anything that can be done to clean that up apart from waiting for the Github's periodic `git gc` to run?

**Comment by purcell** [comment]
Nope, but I wouldn't worry too much about it. Eventually, the issues will hopefully end up closed anyway.

**Comment by Fanael** [comment]
In fact, all of these already are.

**Comment by jlr** [comment]
You guys rock. Thanks for the boost. I thought I left rainbow-delimiters essentially complete and bug free, but a few genuinely annoying bugs were hiding in there. Oh well - we'll pick it up from here.

I'm told people want this mode in Elpa, by the way. We should be conscious of whatever copyright/paperwork issues might be involved with that.
