### ISSUE TITLE
Fork for highlighting blocks

### ISSUE THREAD

**Issue by istib** [jlr/rainbow-delimiters#26]
Sorry, this isn't an actual issue, but I wanted to point out a fork of this excellent which people could find useful:
https://github.com/istib/rainbow-blocks

**Comment by purcell** [comment]
Perhaps mention it on the [Emacswiki page](http://www.emacswiki.org/emacs/RainbowDelimiters) and/or submit a PR adding a mention of `rainbow-blocks` to the README?

**Comment by istib** [comment]
That is indeed a smarter way to go about it. Thanks!
