### ISSUE TITLE
rainbow-delimieter is unbearably slow on large buffer

### ISSUE THREAD

**Issue by tuhdo** [jlr/rainbow-delimiters#29]
On a large buffer (around 5MB), `rainbow-delimiter` slows down editing significantly. Example:
- Download tcl source here: http://sourceforge.net/projects/tcl/
- Open file: **tcl8.6.1/pkgs/sqlite3.8.0/generic/sqlite3.c**
- Go to end of file and try to insert characters. It's very slow. 

I guess `rainbow-delimiter` actually highlights the whole buffer? It should only highlight the current visible page only.

**Comment by purcell** [comment]
So it was fast without `rainbow-delimiters`, but slow with it enabled?

I just tried exactly this in a recent Emacs snapshot, and noticed no issues at all.

> I guess rainbow-delimiter actually highlights the whole buffer? It should only highlight the current visible page only.

No, it hooks into jit-lock, and will only highlight the regions the just-in-time font-lock subsystem tells it to.

So I guess the questions are:
- Which Emacs version do you have? (And if it's old, can you upgrade?)
- Which `rainbow-delimiters.el` version do you have?

**Comment by tuhdo** [comment]
My Emacs version:

> GNU Emacs 24.4.50.2 (x86_64-unknown-linux-gnu, GTK+ Version 3.10.8) of 2014-05-05 on xtuudoo-Satellite-L640

Yes, it was fast without `rainbow-delimiters` enabled and I installed it from MELPA.

Well, I retract my statement about "unbearably slow". I discovered that I was using [highlight-parentehses](https://github.com/nschum/highlight-parentheses.el) to highlight the sexp I'm currently in; this was a major slow down. Without it. using `rainbow-delimiter` was not that bad, but editing experience is still not as smooth as when it is disabled. When I enabled the two together, editing on a mere 5 MB C/C++ file is very slow. 

I use Inconsolata font and a quite large screen (24 inches). So probably there are a lot of text and it takes more time to process the visible region of current buffer.

If nothing can be done, I will close the issue.

**Comment by tuhdo** [comment]
Note: The file I really meant was **sqlite3.c**, not **tclsqlite3.c**. 

Sorry for this mistake. The **sqlite3.c** is 140k lines of code and is 5MB in size, not the other file.

**Comment by purcell** [comment]
Ah, I'll take a look at that other file. BTW, since you've got a recent Emacs, you should use the built-in `show-paren` instead of `highlight-parentheses`. It can even highlight blocks delimited by `def` and `end` in ruby.

**Comment by tuhdo** [comment]
Well, I do use `show-paren-mode`. But `highlight-parentheses` highlights a pair that I'm in without having to move the cursor at the opening/end of the pair. it's quite convenient in Lisp mode to know what sexp I'm currently in whlie in the middle of that sexp. Too bad, I have to remove it for performance reason.

**Comment by purcell** [comment]
I can confirm that rainbow-delimiters does indeed make typing slow at the end of that very large file, when the typing includes opening delimiters like `(`.

But even in the worst case, `rainbow-delimiters-propertize-region` is only being asked to propertize the visible region, so perhaps something is causing it to look further back. I'll maybe investigate further if I get a chance, but I can't offer to do it right now.

> But highlight-parentheses highlights a pair that I'm in without having to move the cursor at the opening/end of the pair. it's quite convenient in Lisp mode to know what sexp I'm currently in whlie in the middle of that sexp.

I quite like `hl-sexp` for that.

**Comment by tuhdo** [comment]
`hl-sexp` is cool. Thanks.

**Comment by tuhdo** [comment]
This info can be helpful: `linum-mode` is also a factor that slows down on large buffer. I have to make Emacs disable it when buffer is larger than 1 MB. So, if you are testing `rainbow-delimiter`, you should turn off `linum-mode`.

**Comment by Fanael** [comment]
The performance regression has been introduced by 2561e9853c. Well fuck. We can't revert it, because that'd unfix #25.

From what I see after adding a few `message` calls to `rainbow-delimiters-syntax-ppss`, the problem is that it's getting called with `pos` being before the position we have cached, rendering the cache unusable and necessitating a full `parse-partial-sexp` from the beginning of the buffer:

```
rainbow-delimiters-syntax-ppss called at 5239569
rainbow-delimiters-syntax-ppss called at 5239570
rainbow-delimiters-syntax-ppss called at 5239573
rainbow-delimiters-syntax-ppss called at 5239574
rainbow-delimiters-syntax-ppss called at 5239569
… can't use cache.
```

We definitely need a smarter cache. I have an idea, but I don't know when I'm going to have the time and motivation to implement it.

**Comment by Fanael** [comment]
@purcell: just in case you're more willing to deal with it than I am at the moment: my idea is to rewrite the cache and make it a trie¹ keyed by buffer position, with the `parse-partial-sexp` states being the values. It will probably be a good idea to insert new values into the cache only when they're more than K (the exact value to be determined experimentally) characters away from the nearest previous value, to avoid using too much memory.

[1] A sorted list might suffice too, but a trie can find, insert and delete in O(1) instead of O(n) and isn't really any harder to implement.

**Comment by purcell** [comment]
Thanks — I’m unlikely to get to this, though! :-)

**Comment by Fanael** [comment]
Patch follows. It uses sorted lists, because I don't know why. It does have scalability problems inherent to sorted lists, but 5M files are not enough for them to arise.

Works for me, if it solves the problem for you too I'll install it.

@purcell: could you review the patch, please? I'm not sure I'm doing it the idiomatic way.

```
 rainbow-delimiters.el | 48 ++++++++++++++++++++++++++++++++----------------
 1 file changed, 32 insertions(+), 16 deletions(-)

diff --git a/rainbow-delimiters.el b/rainbow-delimiters.el
index 2e45225..95a2ee7 100644
--- a/rainbow-delimiters.el
+++ b/rainbow-delimiters.el
@@ -323,22 +323,34 @@ For example: 'rainbow-delimiters-depth-1-face'."
 ;; we build a simple cache around it. This brings the speed to around
 ;; what it used to be, while fixing the bug. See issue #25.

-;; TODO: maybe make the cache a little smarter than just caching the
-;; last call?
-
 (defvar rainbow-delimiters-parse-partial-sexp-cache nil
   "Cache of the last `parse-partial-sexp' call.

-If it's nil, there's nothing in the cache. Otherwise, it's a cons
-cell, where car is the position for which `parse-partial-sexp' was
-called and cdr is the result of the call.")
+It's a list of conses, where car is the position for which `parse-partial-sexp'
+was called and cdr is the result of the call. The list is ordered descending by
+car.")
 (make-variable-buffer-local 'rainbow-delimiters-parse-partial-sexp-cache)

+(defconst rainbow-delimiters-parse-partial-sexp-cache-max-span 20000)
+
 (defun rainbow-delimiters-syntax-ppss-flush-cache (beg _end)
   "Flush the `parse-partial-sexp' cache starting at position BEG."
-  (when (and rainbow-delimiters-parse-partial-sexp-cache
-             (<= beg (car rainbow-delimiters-parse-partial-sexp-cache)))
-    (setq rainbow-delimiters-parse-partial-sexp-cache nil)))
+  (let ((it rainbow-delimiters-parse-partial-sexp-cache))
+    (while (and it (>= (caar it) beg))
+      (setq it (cdr it)))
+    (setq rainbow-delimiters-parse-partial-sexp-cache it)))
+
+(defsubst rainbow-delimiters-syntax-ppss-run (from to oldstate cache-nearest-after)
+  (while (< from to)
+    (let ((newpos (min to (+ from rainbow-delimiters-parse-partial-sexp-cache-max-span))))
+      (let ((state (parse-partial-sexp from newpos nil nil oldstate)))
+        (if (/= newpos to)
+            (if cache-nearest-after
+                (push (cons newpos state) (cdr cache-nearest-after))
+              (push (cons newpos state) rainbow-delimiters-parse-partial-sexp-cache)))
+        (setq oldstate state
+              from newpos))))
+  oldstate)

 (defsubst rainbow-delimiters-syntax-ppss (pos)
   "Parse-Partial-Sexp State at POS, defaulting to point.
@@ -350,12 +362,16 @@ upon.
 This is essentialy `syntax-ppss', only specific to rainbow-delimiters
 to work around a bug."
   (save-excursion
-    (let* ((cache rainbow-delimiters-parse-partial-sexp-cache)
-           (ppss (if (and cache (>= pos (car cache)))
-                     (parse-partial-sexp (car cache) pos nil nil (cdr cache))
-                   (parse-partial-sexp (point-min) pos))))
-      (setq rainbow-delimiters-parse-partial-sexp-cache (cons pos ppss))
-      ppss)))
+    (let ((it rainbow-delimiters-parse-partial-sexp-cache)
+          (prev nil))
+      (while (and it (>= (caar it) pos))
+        (setq prev it)
+        (setq it (cdr it)))
+      (let* ((nearest-after (if (consp prev) prev nil))
+             (nearest-before (if (consp it) (car it) it))
+             (nearest-before-pos (if nearest-before (car nearest-before) (point-min)))
+             (nearest-before-data (if nearest-before (cdr nearest-before) nil)))
+        (rainbow-delimiters-syntax-ppss-run nearest-before-pos pos nearest-before-data nearest-after)))))

 ;;; Nesting level

@@ -480,7 +496,7 @@ Returns t if char at loc meets one of the following conditions:
 - Inside a string.
 - Inside a comment.
 - Is an escaped char, e.g. ?\)"
-  (let ((parse-state (rainbow-delimiters-syntax-ppss loc)))
+  (let ((parse-state (syntax-ppss loc)))
     (or
      (nth 3 parse-state)                ; inside string?
      (nth 4 parse-state)                ; inside comment?
```

**Comment by tuhdo** [comment]
@Fanael I tested it with the original C file I encountered. Your patch improves the performance, but typing still has delay. You must scroll to the end or near end of the file. 

I also create a 8MB rainbow-delimiters2.el like this for testing:

``` shell
cat rainbow-delimiters2.el >> rainbow-delimiters2.el
```

`rainbow-delimiters2.el` is the copy of original rainbow-delimiters.el. I repeated the above command a few times until I got the desired size for testing. Typing at the end of file is also slow, even with the new patch applied.

**Comment by tuhdo** [comment]
@Fanael I tested it again. Your patch does indeed fixed this problem. The slow down with a large buffer above was caused by something else during my testing.

**Comment by purcell** [comment]
Great, committed. :-)

**Comment by Fanael** [comment]
@purcell: I hope MELPA stable will pick up forced tag updates? It turns out there was a bug that caused `(rainbow-delimiters-syntax-ppss 1)` to return nil, which in turn caused an exception in `rainbow-delimiters-depth`.

**Comment by purcell** [comment]
I _think_ we'll pick up forced tags, but it would make sense to just bump the version number for fixes.

**Comment by Fanael** [comment]
Done. In the future, please bear in mind the patches I post to the bug tracker are usually WIP, untested and unstable and therefore unsuitable for tagging as stable. Committing them is OK if they seem to work, though.

**Comment by purcell** [comment]
Yep, my bad: for some reason I forgot that you had commit access to the repo, so I just went ahead and added the code and bumped the version without giving it enough thought. :-)
