### ISSUE TITLE
run-hooks: Symbol's function definition is void: rainbow-delimiters-mode

### ISSUE THREAD

**Issue by ghost** [jlr/rainbow-delimiters#30]
Version: 20140713.1131 
OS: GNU/LInux
Emacs: 24.3

My packages have been installed through the package manager and rainbow-delimiters-20140713.1131 appears in the elpa directory. All other packages work, although I receive 'Symbol's function definition is void: rainbow-delimiters-mode' . 

My .emacs is here: https://github.com/AidyLewis/dotfiles/blob/master/.emacs

I'm on Trusty Tar now, but the same issue occurred on an Amazon t2.micro, which maybe you could test it on.

Many Thanks

Aidy

**Comment by purcell** [comment]
`rainbow-delimiters-mode` is autoloaded, and should therefore be magically available after `package-initialize`, so one of the following is happening:
- The package didn't install cleanly, and the `elpa/rainbow-delimiters-20140713.1131/rainbow-delimiters-autoloads.el` is missing or truncated. If so, delete that dir and reinstall the package.
- `package-initialize` is not looking in the `elpa` directory you think it is.

In any case, start Emacs with `--debug-init` to get a more helpful backtrace.

**Comment by ghost** [comment]
Took @purcell's advice and deleted rainbow-delimiters package from emacs.d/elpa and re-installed.

**Comment by purcell** [comment]
Yay, glad that worked for you.
