### ISSUE TITLE
The default value of rainbow-delimiters-ignore-modes should be nil

### ISSUE THREAD

**Issue by Fanael** [jlr/rainbow-delimiters#33]
The only reason `rainbow-delimiters-ignore-modes` is not `nil` by default is it being a sop to misbehaved upstream projects (see #31).

Please tell the upstream developers to update their code to propertize with `font-lock-face` instead of just `face` so `font-lock-mode` doesn't overwrite their highlighting, so it's possible to remove this workaround from `rainbow-delimiters`.

**Comment by bbatsov** [comment]
I've made [this changes](https://github.com/clojure-emacs/cider/commit/401e81941ce81e9ee70c4f771697e4bef5b04dc9) to CIDER's REPL, but it's still not playing nice with rainbow-delimiters. Any ideas?

**Comment by Fanael** [comment]
What do you mean by not playing nice? Please post a screenshot and the result of `(buffer-string)`.

**Comment by bbatsov** [comment]
My bad. As soon as I did `(buffer-string)` I found the problem - there were a few remaining `face` references that I hadn't updated. You can now remove `cider-repl-mode` from the ignore-modes I guess.

**Comment by Fanael** [comment]
Already removed, see 3a18183db.

**Comment by purcell** [comment]
LOL - I was just about to push an identically-named commit when I saw you'd beaten me to it.

**Comment by Fanael** [comment]
Closing in favor of #40.
