### ISSUE TITLE
check comment-start-skip

### ISSUE THREAD

**Issue by fxbois** [jlr/rainbow-delimiters#36]
In web-mode.el, I do not set `comment-start-skip` (because I have to deal many types of comments), could you test this var before using ?
Some users are reporting issues with web-mode when using rainbow-delimiters

**Comment by Fanael** [comment]
Is 6d488e566 what you mean?

**Comment by Fanael** [comment]
Fixed.

**Comment by therik** [comment]
thank you guys!
tested, working

**Comment by jonnay** [comment]
:+1:
