### ISSUE TITLE
rainbow-delimiters breaks the font-locking in CIDER REPL buffers

### ISSUE THREAD

**Issue by bbatsov** [jlr/rainbow-delimiters#37]
See [this ticket](https://github.com/clojure-emacs/cider/issues/749).

Seems to me something was changed around the time the ticket was reported as I had been using rainbow-delimiters for quite some time without any problems.

**Comment by Fanael** [comment]
See #33.

**Comment by bbatsov** [comment]
OK, I'll replace our usages of `'face` with `'font-lock-face`. I wonder how I didn't learn about this earlier.
