### ISSUE TITLE
Remove global-rainbow-delimiters-mode.

### ISSUE THREAD

**Issue by Fanael** [jlr/rainbow-delimiters#40]
Supporting it is more trouble than it's worth.

It's deprecated since e2a67de8e7.

**Comment by Fanael** [comment]
#41 is to be merged in about two weeks.

**Comment by dpathakj** [comment]
I suggest leaving the function in, but having it loudly indicate that it is not doing anything, and that it's recommended to add a 'prog-mode-hook instead. Removing it will cause unnecessary confusion.

**Comment by Fanael** [comment]
I know, and that's why it's deprecated for now. It's not going to stay deprecated forever, though, and I _am_ going to remove it.
