### ISSUE TITLE
rainbow-delimiters depends on Emacs 24.3

### ISSUE THREAD

**Issue by Fanael** [jlr/rainbow-delimiters#46]
Introduced in 3dfd3fa9b11.

The culprit is a [generalized push](https://github.com/jlr/rainbow-delimiters/blob/d35b9923788893185e8611a2504ff7cdd8de76cc/rainbow-delimiters.el#L300).

**Comment by Fanael** [comment]
Which brings an important question: should I drop Emacs <= 24.2 support, or replace it with `setcdr + cons + cdr`, so Emacs 24.2 and older are still supported?

The fact that nobody noticed it until now probably shows how many people still use Emacs 24.2 or older.

**Comment by purcell** [comment]
I'd be inclined to continue to support older versions if it is straightforward to do so.

**Comment by Fanael** [comment]
Fixed in both branches.

**Comment by Fanael** [comment]
I'm now wondering if I shouldn't just delete it, as it looks like dead code to me.

`rainbow-delimiters-syntax-ppss-run` will add all the intermediate results to the cache, so it always leaves the cache in the following state:

```
(20001 . state-0)
(40001 . state-1)
(60001 . state-2)
…
(*farthest-visited* . state-n)
```

where the elements are always exactly 20,000 (aka `rainbow-delimiters-parse-partial-sexp-cache-max-span`) positions apart, so when we reach `(if (/= newpos to) …)` with any position between the cached ones the condition is always false, so there's nothing to insert. (BTW, it should be a `when`.)

The only operation that deletes elements from the cache is the before change hook, which deletes all elements after a position, so the last position is always before or equal to `*farthest-visited*`.

There's just no way for a gap bigger than `rainbow-delimiters-parse-partial-sexp-cache-max-span` positions to occur without the user changing that variable when the cache is not empty… but that variable is an implementation detail, so we're dealing with a malicious (or one just too curious for their own good) user, and a malicious user could just do `(fset #'rainbow-delimiters-syntax-ppss-run #'ignore)`, and there's nothing protecting us against that.

Am I missing something?

**Comment by purcell** [comment]
I'm a little bit out of the loop with the details, to be honest: I don't think there's anyone who understands the package as much as you right now, so I think you should feel free to follow your intuition.

**Comment by Fanael** [comment]
Well, that's a shame. I replaced that `setcdr` with `(error "the impossible happened?")`. Will remove the test entirely if the error won't fire.
