### ISSUE TITLE
Not working with Emacs 24 preview?

### ISSUE THREAD

**Issue by kwstat** [jlr/rainbow-delimiters#8]
For me, if i use Emacs 23, the parens are fontified properly, but using the latest Emacs 24 preview (24.0.95.1), I am not getting correct fontification.  

Could be just my configuration, but it might be worth checking...

**Comment by jlr** [comment]
Hi, I just updated to the latest emacs bzr and it looks OK to me, at least when viewing at elisp files. Was this editor-wide or only a problem when editing a certain language, and what was it doing wrong? Was the mode not fontifying anything at all, or were matching pairs of delims getting highlighted in confusing/wrong colors?
Thanks - if you have more info I'll be happy to look into it.

**Comment by kwstat** [comment]
Thanks for checking.  I was afraid it wasn't a simple problem.  It looks
like the problem only happens when I use the "Emacs Speaks Statistics"
package to edit R code.  In that mode, the font-locking is minimal,
sometimes non-existent.  My guess is the problem is in the interaction of
rainbow-mode and r-mode.

Kevin

On Mon, Apr 23, 2012 at 5:34 PM, jlr <
reply@reply.github.com

> wrote:
> 
> Hi, I just updated to the latest emacs bzr and it looks OK to me, at least
> when viewing at elisp files. Was this editor-wide or only a problem when
> editing a certain language, and what was it doing wrong? Was the mode not
> fontifying anything at all, or were matching pairs of delims getting
> highlighted in confusing/wrong colors?
> Thanks - if you have more info I'll be happy to look into it.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jlr/rainbow-delimiters/issues/8#issuecomment-5293598

## 

Kevin Wright

**Comment by jlr** [comment]
If you're turning on the mode and seeing no change (no highlighting at all), I saw the same thing in org-mode but haven't looked into it.
But if you're getting mismatched colors (e.g. parens turning red when they shouldn't, open&close parens different colors), the new version I just put out yesterday would probably fix it because it removes the only assumption I can see about what's going to be in the syntax-table.
If you're seeing that it'd be worth trying the new one.

**Comment by kwstat** [comment]
I think the problem is fixed in the new version.

Thank you!

Kevin

On Sat, Apr 28, 2012 at 11:41 PM, jlr
reply@reply.github.com
wrote:

> If you're turning on the mode and seeing no change (no highlighting at all), I saw the same thing in org-mode but haven't looked into it.
> But if you're getting mismatched colors (e.g. parens turning red when they shouldn't, open&close parens different colors), the new version I just put out yesterday would probably fix it because it removes the only assumption I can see about what's going to be in the syntax-table.
> If you're seeing that it'd be worth trying the new one.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/jlr/rainbow-delimiters/issues/8#issuecomment-5402638

## 

Kevin Wright
